apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: versio-dev-ci-run-
spec:
  pipelineRef:
    name: versio-dev-ci

  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi